### ISSUE TITLE
How to do the camera calibration

### ISSUE THREAD

**Issue by SaddamBInSyed** [Ank-Cha/Social-Distancing-Analyser-COVID-19#1]
@Ank-Cha 

Thanks for your work.

could you please advise how to do the camera calibration in the code?

I tried your code with webcam and close object detection result is poor.

highly appreciate your advice on this.

**Comment by Ank-Cha** [comment]
You need to map out the dimensions and coordinates of pathways and generate a function that compensates for the orientation and size decrement caused by object distance from the camera.

**Comment by SaddamBInSyed** [comment]
Thanks for your response.

As stated, Do u have any plan to implement "auto calibration" on coming days .?

**Comment by Ank-Cha** [comment]
yes, I am working on it
