### ISSUE TITLE
licencing issue

### ISSUE THREAD

**Issue by ghost** [Ank-Cha/Social-Distancing-Analyser-COVID-19#2]
You are restricting code on Github without an open-source license protecting your work. This means you have little to no power over who can do what with your code without a proper license. You are also publically shaming people who take credit for your code (despite there being a lack of a license, meaning anyone can take credit for your code legally and you can't do a thing) which can be viewed as a violation of Github's terms of use.

I recommend the  GNU GPL license (https://www.gnu.org/licenses/gpl-3.0.html) to follow your restrictions, but you may want to review this license to make sure it follows with all of your terms. It is a strong copyleft license that can protect your work.
GNU GPL does allow for commercial use, so consider dual-licensing with the Commons Clause license (https://commonsclause.com/)

Lastly, to fully comply with Github's terms, I recommend not blasting others' social media on Github. You can modify your README to remove the offense, or you can leave it up there and Github can take action against you for DOXXing. It is truly up to you.

Have a fine day and take my advice into consideration!

**Comment by Ank-Cha** [comment]
thank you for the advice

**Comment by Ank-Cha** [comment]
From GitHub's licensing help page:

You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. The Open Source Guide provides additional guidance on choosing the correct license for your project.


Please improve your knowledge before commenting about the things you know nothing about!!

**Comment by Ank-Cha** [comment]
btw thanks for the recommendation of dual licencing, i didnt know you can do that

**Comment by BKenzie7** [comment]
Did you seriously be a jerk to someone who was only trying to help then thank them? How is that supposed to work? Whatever dude, just trying to tell you that you should probably get a license if you are going to host on an open-source platform, and what you were doing was still DOXXing, regardless of licensing.
