### ISSUE TITLE
Video Speed

### ISSUE THREAD

**Issue by ShounakCy** [Ank-Cha/Social-Distancing-Analyser-COVID-19#5]
Hi, My CPU has a NVIDIA  geforce 940MX config, still the video lags when I run the code. As suggested I have even tried the same with the tiny versions, but the speed improved by 10-20 % only. Can you suggest if anywhere else it has to be tuned in your code to obtain the correct fps.

Thanks

**Comment by Ank-Cha** [comment]
The code runs on cpu. ....... will make a gpu version soon
try Single shot detector for better performance

**Comment by ZIKO94ZIKO** [comment]
same issue ,, any update ?

**Comment by eagleanurag** [comment]
> 
> 
> The code runs on cpu. ....... will make a gpu version soon
> try Single shot detector for better performance

how to single shot ?
